Traceback (most recent call last):
  File "pylcio_powered_2ascii.py", line 283, in <module>
    slcio_file, ascii_out_dir, ev_start, ev_stop = validate_command_line_args()
  File "pylcio_powered_2ascii.py", line 260, in validate_command_line_args
    if len(sys.argv) not in [3, 5]: raise Exception(help_string)
Exception: The script must be called with 2 or 4 arguments as:
$ python pylcio_powered_2ascii.py slcio_file ascii_out_dir ev_start ev_stop
- slcio_file: File with the reconstructed information in LCIO format.
- ascii_out_dir: Folder to write the ASCII output to.
    Its parent must exist. The folder itself can exist, but must be empty then.
- ev_start ev_stop: Integers. Specify both or neither of them. Will process
    (ev_stop - ev_start) events. Use ev_stop=-1 to exhaust the file.

